kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"ms-dev:build-33","namespace":"jeschb"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ms-dev\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  name: ms-dev
  namespace: jeschb
  labels:
    app: ms-dev
    app.kubernetes.io/component: ms-dev
    app.kubernetes.io/instance: ms-dev
    app.kubernetes.io/name: ms-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: ms-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
