apiVersion: template.openshift.io/v1
kind: Template
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: APP_NAME
    namespace: PROJECT_NAME
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    volumeMode: Filesystem
  status:
    phase: Bound
    accessModes:
      - ReadWriteMany
    capacity:
      storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: APP_NAME
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: APP_NAME
      app.kubernetes.io/part-of: PROJECT_NAME
      app.openshift.io/runtime: spring-boot
    name: APP_NAME
    namespace: PROJECT_NAME
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: APP_NAME
      type: Recreate
    template:
      metadata:
        labels:
          app: APP_NAME
          deploymentconfig: APP_NAME
      spec:
        containers:
          - name: APP_NAME
            image: image-registry.openshift-image-registry.svc:5000/PROJECT_NAME/APP_NAME:BUILD_NUMBER
            ports:
            - name: tcp8080
              containerPort: 8080
              protocol: TCP
            envFrom:
            - configMapRef:
                name: APP_NAME
            - secretRef:
                name: APP_NAME
            volumeMounts:
              - name: logs-APP_NAME
                mountPath: /logs
        volumes:
          - name: logs-APP_NAME
            persistentVolumeClaim:
              claimName: APP_NAME
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    name: APP_NAME
    namespace: PROJECT_NAME
  spec:
    ports:
      - name: APP_NAME
        protocol: TCP
        port: 80
        targetPort: 8080
    selector:
      app: APP_NAME
    type: LoadBalancer
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: APP_NAME
    namespace: PROJECT_NAME
  spec:
    host: APP_NAME-PROJECT_NAME.cajaarequipa.pe
    to:
      kind: Service
      name: APP_NAME
      weight: 100
    port:
      targetPort: APP_NAME